export const parkingplaces = [
  {
    id: "1",
    title: "الموقف الاول",
    capacity: 5,
    avaliable: 2,

    // subtitle: "الموقف الاوالموقف الاوالموقف الاوالموقف الاوالموقف الاو ",
    imgpath: ["./images/backgroundjpg.jpg", "./images/park.jpg", "./images/homeimg.jpg"],
  },
  {
    id: "2",
    title: "الموقف الثاني",
    // subtitle: "الموقف الاوالموقف الاوالموقف الاوالموقف الاوالموقف الاوالموقف الاو ",
    capacity: 5,
    avaliable: 2,
    imgpath: ["/images/backgroundjpg.jpg", "/images/park.jpg", "/images/homeimg.jpg"],
  },
  {
    id: "2",
    title: "الموقف الثاني",
    // subtitle: "الموقف الاوالموقف الاوالموقف الاوالموقف الاوالموقف الاوالموقف الاو ",
    capacity: 5,
    avaliable: 2,
    imgpath: ["/images/backgroundjpg.jpg", "/images/park.jpg", "/images/homeimg.jpg"],
  },
  {
    id: "2",
    title: "الموقف الثاني",
    // subtitle: "الموقف الاوالموقف الاوالموقف الاوالموقف الاوالموقف الاوالموقف الاو ",
    capacity: 5,
    avaliable: 2,
    imgpath: ["/images/backgroundjpg.jpg", "/images/park.jpg", "/images/homeimg.jpg"],
  },
  {
    id: "2",
    title: "الموقف الثاني",
    // subtitle: "الموقف الاوالموقف الاوالموقف الاوالموقف الاوالموقف الاوالموقف الاو ",
    capacity: 5,
    avaliable: 2,
    imgpath: ["/images/backgroundjpg.jpg", "/images/park.jpg", "/images/homeimg.jpg"],
  },
  {
    id: "2",
    title: "الموقف الثاني",
    // subtitle: "الموقف الاوالموقف الاوالموقف الاوالموقف الاوالموقف الاوالموقف الاو ",
    capacity: 5,
    avaliable: 2,
    imgpath: ["/images/backgroundjpg.jpg", "/images/park.jpg", "/images/homeimg.jpg"],
  },
  {
    id: "2",
    title: "الموقف الثاني",
    // subtitle: "الموقف الاوالموقف الاوالموقف الاوالموقف الاوالموقف الاوالموقف الاو ",
    capacity: 5,
    avaliable: 2,
    imgpath: ["/images/backgroundjpg.jpg", "/images/park.jpg", "/images/homeimg.jpg"],
  },
  {
    id: "2",
    title: "الموقف الثاني",
    // subtitle: "الموقف الاوالموقف الاوالموقف الاوالموقف الاوالموقف الاوالموقف الاو ",
    capacity: 5,
    avaliable: 2,
    imgpath: ["/images/backgroundjpg.jpg", "/images/park.jpg", "/images/homeimg.jpg"],
  },
  {
    id: "3",
    title: " الموقف الثالث",
    capacity: 5,
    avaliable: 2,

    // subtitle: "الموقف الاوالموقف الاوالموقف الاوالموقف الاوالموقف الاوالموقف الاو ",
    imgpath: ["/images/backgroundjpg.jpg", "/images/park.jpg", "/images/homeimg.jpg"],
  },
  {
    id: "4",
    title: "الموقف الرابع",
    capacity: 5,
    avaliable: 2,

    // subtitle: "الموقف الاوالموقف الاوالموقف الاوالموقف الاوالموقف الاوالموقف الاو ",
    imgpath: ["/images/backgroundjpg.jpg", "/images/park.jpg", "/images/homeimg.jpg"],
  },
];
